opciones:                  # Opciones generales
  eliminar:                false
  tabla:                   creditos
  anchogrid:               1250
  filas:                   10
  titulo:                  Información a Importar
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Cedula
  tipo:                    t
  nombrecampo:             id_cliente_persona
  esgrabable:              true  
  html:                    [type="text", size="10" ]
2:       # Columna 2
  titulo:                  Factura
  tipo:                    t
  nombrecampo:             factura
  esgrabable:              true
  html:                    [type="text", size="10" ]
3:
  titulo:                  Fecha Compra
  tipo:                    f
  esgrabable:              true
  nombrecampo:             fecha_compra
  esgrabable:              true  
  html:                    [type="text", size="10" ]
4:
  titulo:                  Fecha Operacion
  tipo:                    f
  nombrecampo:             fecha_operacion
  esgrabable:              true  
  html:                    [type="text", size="10" ]
5:
  titulo:                  Monto
  tipo:                    m
  nombrecampo:             monto
  esnumerico:              true
  html:                    [type="text", size="10", readonly=true ]
6:
  titulo:                  Pago Mensual
  tipo:                    m
  nombrecampo:             pago_mes
  esnumerico:              true
  html:                    [type="text", size="10", readonly=true ]
7:
  titulo:                  Numero de Giros
  tipo:                    m
  nombrecampo:             num_giros
  esnumerico:              true
  html:                    [type="text", size="10", readonly=true ]
8:
  titulo:                  Experiencia
  tipo:                    m
  nombrecampo:             experiencia
  esnumerico:              true
  html:                    [type="text", size="10", readonly=true ]
  estotal:                 [true, caajuoc_monaju]
9:
  titulo:                  Estado
  tipo:                    m
  nombrecampo:             estado
  esnumerico:              true
  html:                    [type="text", size="10", readonly=true ]
  estotal:                 [true, caajuoc_monaju]  