options:                   # Opciones generales
  delete:                  false
  classname:               creditos
  width:                   1250
  rows:                    10
  title:                   Información a Importar
1:       # Columna 1
  title:                   Cedula
  type:                    t
  field:                   id_cliente_persona
  save:                    true  
  catalog:                 [caregart, sf_admin_edit_form, {desart: 2}, afterEdit ]
2:       # Columna 2
  title:                   Factura
  type:                    t
  field:                   factura
  save:                    true
3:
  title:                   Fecha Compra
  type:                    f
  save:                    true
  field:                   fecha_compra
  save:                    true  
4:
  title:                   Fecha Operacion
  type:                    f
  field:                   fecha_operacion
  save:                    true  
5:
  title:                   Monto
  type:                    m
  field:                   monto
6:
  title:                   Pago Mensual
  type:                    m
  field:                   pago_mes
7:
  title:                   Numero de Giros
  type:                    d
  field:                   num_giros
8:
  title:                   Experiencia
  type:                    d
  field:                   experiencia
  issum:                   [true, caajuoc_monaju]
9:
  title:                   Estado
  type:                    m
  field:                   estado
  issum:                   [true, caajuoc_monaju]
10:
  title:                   Prueba Combo
  type:                    c
  field:                   factura
  comboelements:           {12: uno, 13: dos, 14: tres, 15:cuatro }
#  comboelements:           [uno, dos, tres, cuatro ]
  
  