<?php


/**
 * This class defines the structure of the 'clientes' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Apr 29 01:37:12 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ClientesTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ClientesTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('clientes');
		$this->setPhpName('Clientes');
		$this->setClassname('Clientes');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID_CLIENTE', 'IdCliente', 'INTEGER', true, 11, null);
		$this->addColumn('ID_CASA_COMERCIAL', 'IdCasaComercial', 'INTEGER', false, 11, 0);
		$this->addColumn('NOMBRE', 'Nombre', 'VARCHAR', true, 30, '');
		$this->addColumn('RIF', 'Rif', 'VARCHAR', false, 15, null);
		$this->addColumn('NIT', 'Nit', 'VARCHAR', false, 15, null);
		$this->addColumn('DIRECCION', 'Direccion', 'VARCHAR', false, 50, null);
		$this->addColumn('TELEFONO', 'Telefono', 'VARCHAR', false, 20, null);
		$this->addColumn('FAX', 'Fax', 'VARCHAR', false, 20, null);
		$this->addColumn('CELULAR', 'Celular', 'VARCHAR', false, 20, null);
		$this->addColumn('EMAIL', 'Email', 'VARCHAR', false, 50, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // ClientesTableMap
