<?php


/**
 * This class defines the structure of the 'clientes_conf' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Apr 29 01:37:12 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ClientesConfTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ClientesConfTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('clientes_conf');
		$this->setPhpName('ClientesConf');
		$this->setClassname('ClientesConf');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(false);
		// columns
		$this->addPrimaryKey('ID_CLIENTE', 'IdCliente', 'INTEGER', true, 11, 0);
		$this->addColumn('DESCUENTO', 'Descuento', 'INTEGER', true, 11, 0);
		$this->addColumn('CONSULTAS', 'Consultas', 'INTEGER', true, 11, 0);
		$this->addColumn('APORTES', 'Aportes', 'INTEGER', true, 11, 0);
		$this->addColumn('FECHA_INI', 'FechaIni', 'DATE', true, null, '0000-00-00');
		$this->addColumn('STATUS', 'Status', 'INTEGER', true, 1, 1);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // ClientesConfTableMap
