<?php


/**
 * This class defines the structure of the 'creditos' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Dec 27 14:37:58 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class CreditosTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.CreditosTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('creditos');
		$this->setPhpName('Creditos');
		$this->setClassname('Creditos');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11, null);
		$this->addColumn('ID_CLIENTE_PERSONA', 'IdClientePersona', 'INTEGER', true, 11, 0);
		$this->addColumn('FACTURA', 'Factura', 'VARCHAR', true, 20, '');
		$this->addColumn('FECHA_COMPRA', 'FechaCompra', 'DATE', true, null, '0000-00-00');
		$this->addColumn('FECHA_OPERACION', 'FechaOperacion', 'DATE', true, null, '0000-00-00');
		$this->addColumn('MONTO', 'Monto', 'DOUBLE', true, null, 0);
		$this->addColumn('PAGO_MES', 'PagoMes', 'DOUBLE', true, null, 0);
		$this->addColumn('NUM_GIROS', 'NumGiros', 'TINYINT', true, 4, 0);
		$this->addColumn('EXPERIENCIA', 'Experiencia', 'TINYINT', true, 4, 0);
		$this->addColumn('ESTADO', 'Estado', 'TINYINT', true, 4, 0);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // CreditosTableMap
