<?php


/**
 * This class adds structure of 'creditos' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sun Mar 29 23:53:01 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class CreditosMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.CreditosMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(CreditosPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(CreditosPeer::TABLE_NAME);
		$tMap->setPhpName('Creditos');
		$tMap->setClassname('Creditos');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11);

		$tMap->addColumn('ID_CLIENTE_PERSONA', 'IdClientePersona', 'INTEGER', true, 11);

		$tMap->addColumn('FACTURA', 'Factura', 'VARCHAR', true, 20);

		$tMap->addColumn('FECHA_COMPRA', 'FechaCompra', 'DATE', true, null);

		$tMap->addColumn('FECHA_OPERACION', 'FechaOperacion', 'DATE', true, null);

		$tMap->addColumn('MONTO', 'Monto', 'DOUBLE', true, null);

		$tMap->addColumn('PAGO_MES', 'PagoMes', 'DOUBLE', true, null);

		$tMap->addColumn('NUM_GIROS', 'NumGiros', 'TINYINT', true, 4);

		$tMap->addColumn('EXPERIENCIA', 'Experiencia', 'TINYINT', true, 4);

		$tMap->addColumn('ESTADO', 'Estado', 'TINYINT', true, 4);

	} // doBuild()

} // CreditosMapBuilder
