<?php


/**
 * This class defines the structure of the 'detalle_facturas' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Apr 29 01:37:13 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class DetalleFacturasTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.DetalleFacturasTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('detalle_facturas');
		$this->setPhpName('DetalleFacturas');
		$this->setClassname('DetalleFacturas');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addColumn('ID_FACTURA', 'IdFactura', 'INTEGER', true, 11, 0);
		$this->addColumn('CEDULA_USUARIO', 'CedulaUsuario', 'INTEGER', true, 11, 0);
		$this->addColumn('ID_PERSONA', 'IdPersona', 'VARCHAR', true, 15, '');
		$this->addColumn('FECHA_HORA', 'FechaHora', 'TIMESTAMP', true, null, '0000-00-00 00:00:00');
		$this->addColumn('STATUS', 'Status', 'INTEGER', true, 1, 0);
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // DetalleFacturasTableMap
