<?php


/**
 * This class defines the structure of the 'empresa_conf' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Dec 27 14:37:59 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class EmpresaConfTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.EmpresaConfTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('empresa_conf');
		$this->setPhpName('EmpresaConf');
		$this->setClassname('EmpresaConf');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addColumn('ID_CLIENTE', 'IdCliente', 'INTEGER', true, 11, 0);
		$this->addColumn('WEB', 'Web', 'VARCHAR', true, 50, '');
		$this->addColumn('PRECIO_OK1', 'PrecioOk1', 'FLOAT', true, null, 0);
		$this->addColumn('PRECIO_OK2', 'PrecioOk2', 'FLOAT', true, null, 0);
		$this->addColumn('PRECIO_OK3', 'PrecioOk3', 'FLOAT', true, null, 0);
		$this->addColumn('PRECIO_OK4', 'PrecioOk4', 'FLOAT', true, null, 0);
		$this->addColumn('PRECIO_FALLIDA', 'PrecioFallida', 'FLOAT', true, null, 0);
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // EmpresaConfTableMap
