<?php


/**
 * This class defines the structure of the 'personas_naturales' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Apr 29 01:37:15 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class PersonasNaturalesTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PersonasNaturalesTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('personas_naturales');
		$this->setPhpName('PersonasNaturales');
		$this->setClassname('PersonasNaturales');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(false);
		// columns
		$this->addPrimaryKey('CEDULA', 'Cedula', 'VARCHAR', true, 15, '');
		$this->addColumn('NOMBRE', 'Nombre', 'VARCHAR', true, 30, '');
		$this->addColumn('APELLIDO', 'Apellido', 'VARCHAR', true, 30, '');
		$this->addColumn('TELEFONO', 'Telefono', 'VARCHAR', false, 15, null);
		$this->addColumn('CELULAR', 'Celular', 'VARCHAR', false, 15, null);
		$this->addColumn('PROFESION', 'Profesion', 'VARCHAR', false, 16, null);
		$this->addColumn('NACIONALIDAD', 'Nacionalidad', 'CHAR', false, null, 'VENEZOLANO');
		$this->addColumn('FECHA_NAC', 'FechaNac', 'DATE', false, null, null);
		$this->addColumn('SEXO', 'Sexo', 'CHAR', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // PersonasNaturalesTableMap
