<?php


/**
 * This class adds structure of 'personas_juridicas' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sun Mar 29 23:53:01 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class PersonasJuridicasMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PersonasJuridicasMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(PersonasJuridicasPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(PersonasJuridicasPeer::TABLE_NAME);
		$tMap->setPhpName('PersonasJuridicas');
		$tMap->setClassname('PersonasJuridicas');

		$tMap->setUseIdGenerator(false);

		$tMap->addPrimaryKey('RIF', 'Rif', 'VARCHAR', true, 15);

		$tMap->addColumn('NIT', 'Nit', 'VARCHAR', true, 10);

		$tMap->addColumn('NOMBRE', 'Nombre', 'VARCHAR', true, 30);

		$tMap->addColumn('TELEFONO', 'Telefono', 'VARCHAR', false, 15);

		$tMap->addColumn('DIRECCION', 'Direccion', 'VARCHAR', false, 100);

		$tMap->addColumn('FAX', 'Fax', 'VARCHAR', false, 15);

		$tMap->addColumn('EMAIL', 'Email', 'VARCHAR', false, 30);

	} // doBuild()

} // PersonasJuridicasMapBuilder
