<?php


/**
 * This class adds structure of 'usuarios' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sun Mar 29 23:53:01 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class UsuariosMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.UsuariosMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(UsuariosPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(UsuariosPeer::TABLE_NAME);
		$tMap->setPhpName('Usuarios');
		$tMap->setClassname('Usuarios');

		$tMap->setUseIdGenerator(true);

		$tMap->addColumn('CEDULA', 'Cedula', 'INTEGER', true, 11);

		$tMap->addColumn('ID_CLIENTE', 'IdCliente', 'INTEGER', true, 11);

		$tMap->addColumn('PWD', 'Pwd', 'VARCHAR', true, 50);

		$tMap->addColumn('NOMBRE', 'Nombre', 'VARCHAR', true, 20);

		$tMap->addColumn('APELLIDO', 'Apellido', 'VARCHAR', true, 20);

		$tMap->addColumn('TELEFONO', 'Telefono', 'VARCHAR', false, 15);

		$tMap->addColumn('CELULAR', 'Celular', 'VARCHAR', false, 15);

		$tMap->addColumn('NACIONALIDAD', 'Nacionalidad', 'CHAR', false, null);

		$tMap->addColumn('ID_NIVEL', 'IdNivel', 'TINYINT', true, 1);

		$tMap->addColumn('FECHA', 'Fecha', 'DATE', false, null);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

	} // doBuild()

} // UsuariosMapBuilder
