dev:
  propel:
    param:
      classname: DebugPDO
test:
  propel:
    param:
      classname: DebugPDO
all:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'mysql:host=localhost;dbname=creditum'
#      username: geuser
#      password: ge123456789
      username: root
      password: root
      encoding: utf8
      persistent: true
      pooling: true
